export type Capability = "Macchina" | "Prodotto" | "Reparto" | "Fabbrica" | "Sistema";

export const domains = [
  "Meccanica",
  "Design di prodotto",
  "Automazione",
  "Industrializzazione",
  "Operations",
  "Sistemi digitali",
  "Dati & IA",
  "Governance",
] as const;

export type Domain = (typeof domains)[number];

export type CaseStudy = {
  id: string;
  number: string;
  title: string;
  context: string;
  period: string;
  capability: Capability;
  summary: string;
  premise: string;
  move: string;
  result: string;
  implication: string;
  featured?: boolean;
  fundamental?: boolean;
};

export const capabilities: Capability[] = [
  "Macchina",
  "Prodotto",
  "Reparto",
  "Fabbrica",
  "Sistema",
];

const chronologicalCases: CaseStudy[] = [
  {
    id: "rettifiche-cnc",
    number: "01",
    title: "La quota cambiava con la temperatura",
    context: "BIC Italia | Co Stampi",
    period: "1994–2002",
    capability: "Macchina",
    summary: "A un giovane tecnico fu affidato il passaggio dalle rettifiche manuali al CNC, mentre una deriva millesimale continuava a sottrarsi alle compensazioni.",
    premise: "La Kellenberger era una tecnologia nuova per il reparto. Il corso con un tecnico tedesco doveva superare anche la barriera linguistica, ma il problema reale iniziò quando la quota non rimase stabile.",
    move: "La deriva fu collegata alla temperatura del fluido di processo. Un refrigeratore stabilizzò la lavorazione; un PC recuperato portò gestione e storico dei programmi fuori dal bordo macchina.",
    result: "La macchina divenne più stabile e veloce, i non conformi diminuirono e i programmi diventarono conservabili e riutilizzabili.",
    implication: "La responsabilità tecnica comincia quando si smette di compensare il sintomo e si ridisegna ciò che lo produce.",
    featured: true,
  },
  {
    id: "automazione-piegatura",
    number: "02",
    title: "Il limite non era la piegatrice. Era la cinematica del robot",
    context: "A.R. Quadri",
    period: "2015–2025",
    capability: "Macchina",
    summary: "Piegatrice, braccio robotico, tavola di riposizionamento e laser incisore integrati in una sola sequenza di lavorazione e identificazione.",
    premise: "Asservire la piegatrice non bastava. Geometria del pezzo, cambi di presa, riposizionamenti e marcatura interrompevano ancora il ciclo e restituivano il processo all’operatore.",
    move: "La tavola sul piano di carico rese possibili i riposizionamenti richiesti dalla cinematica del braccio; piegatrice, robot e laser furono coordinati fino all’incisione di logo, numero seriale e altri dati.",
    result: "Manipolazione, piegatura, riposizionamento e identificazione divennero un unico flusso coordinato; i miglioramenti restano qualitativi perché MZB non contiene metriche prima e dopo.",
    implication: "L’automazione reale include tutto ciò che normalmente costringe il processo ad aspettare una persona.",
    featured: true,
  },
  {
    id: "robolaser-applyca",
    number: "03",
    title: "«Alla fine l’abbiamo fatta»",
    context: "Applyca",
    period: "Concept antecedente · conferma 2025",
    capability: "Macchina",
    summary: "Dalle indicazioni per una cella con vero laser e robot antropomorfo alla successiva realizzazione industriale Applyca.",
    premise: "Nel settore degli armadi elettrici, le soluzioni esistenti lasciavano intravedere il limite di una macchina confinata a una sola tecnologia e a un solo campo d’impiego.",
    move: "In un confronto tecnico nato in fiera fu definito un concept capace, con la stessa architettura, di lavorare lamiera piana e quadri elettrici già montati.",
    result: "Nel 2025 arrivò una conferma diretta: la macchina era stata progettata seguendo quelle indicazioni. La soluzione pubblica Applyca ne documenta l’evoluzione industriale e le funzioni finali.",
    implication: "Un’idea industriale diventa prova quando altri riescono a costruirla, farla evolvere e portarla davanti al mercato.",
    featured: true,
    fundamental: true,
  },
  {
    id: "wmc-inside",
    number: "04",
    title: "La smart TV non aveva ancora un nome",
    context: "Hantarex",
    period: "2002–2005",
    capability: "Prodotto",
    summary: "Anni prima che la smart TV diventasse una categoria di mercato, WMC Inside univa televisore, PC, contenuti digitali e telecomando in un prodotto reale.",
    premise: "L'esperienza personale con Windows Media Center aveva già reso visibile una convergenza che il mercato trattava ancora come mondi separati: TV, computer, rete e librerie digitali.",
    move: "Il primo prototipo funzionante fu ideato, progettato, integrato e assemblato interamente in prima persona, lavorando anche fuori orario. Il design su due piani riduceva la massa percepita del PC posteriore e conservava l'identità di un televisore.",
    result: "Il prototipo divenne WMC Inside, prodotto Hantarex documentato e commercializzato. L'azienda e il prodotto ricevettero due Green Button Award Microsoft nel 2004 e nel 2005; Hantarex ne curò industrializzazione e unità commerciali.",
    implication: "Non è una lettura costruita dopo l'arrivo delle smart TV: manuali, immagini e riconoscimenti documentano che quell'oggetto esisteva già.",
    featured: true,
    fundamental: true,
  },
  {
    id: "fiumicino-digital",
    number: "05",
    title: "Diciannove totem non erano diciannove prototipi",
    context: "Metalquadri · CBS Outdoor",
    period: "2008–2011",
    capability: "Prodotto",
    summary: "Design, realizzazione e installazione della prima fornitura di 19 totem digitali portrait da 55 pollici per Fiumicino.",
    premise: "La commessa era acquisita e il design era affidato a Manuel. La purezza del frontale richiedeva un vetro privo di fissaggi visibili, ma il 3M VHB era ancora percepito internamente come un semplice biadesivo.",
    move: "Dopo aver studiato il sistema VHB e la sua idoneità all’applicazione, Manuel ne sostenne l’uso e governò progettazione e realizzazione fino all’installazione della prima fornitura.",
    result: "Diciannove unità furono realizzate e installate con quella soluzione, insieme ad aggiornamento in tempo reale, Wi-Fi e proximity marketing. Il PDF di progetto indica circa 975.000 passeggeri ogni quattordici giorni.",
    implication: "La purezza del design dipende anche dalla capacità di assumersi la responsabilità tecnica di una scelta che gli altri non riconoscono ancora.",
    featured: true,
  },
  {
    id: "safemate-classe-ii",
    number: "06",
    title: "Da un foglio bianco a una linea da 5.000 unità",
    context: "Euroclone · SafeMate Classe II",
    period: "2015–2018",
    capability: "Prodotto",
    summary: "Concept, architettura, prototipi, prove, certificazione e avvio produttivo coordinati in circa sei mesi.",
    premise: "Una cabina di sicurezza microbiologica deve tradurre protezione, contenimento, pulibilità, conformità e producibilità in un solo prodotto.",
    move: "Architettura tridimensionale, stampa 3D FDM, lavorazioni laser, verifiche funzionali e coordinamento della certificazione e dell’avvio produttivo.",
    result: "Nuova versione a catalogo e in produzione in tre taglie; linee dimensionate per una capacità prevista di circa 5.000 unità annue.",
    implication: "Il prodotto è completo solo quando l’impresa possiede anche il sistema capace di ripeterlo.",
    featured: true,
    fundamental: true,
  },
  {
    id: "virus-3",
    number: "07",
    title: "Il rischio doveva restare dentro. L’operatore doveva poter lavorare",
    context: "Euroclone · con Michele Guarino",
    period: "2015–2018",
    capability: "Prodotto",
    summary: "Contenimento biologico, lavoro umano, pulibilità e industrializzazione trattati come una sola architettura.",
    premise: "La barriera totale non può trasformare ogni gesto dell’operatore in un nuovo rischio operativo.",
    move: "Con Michele Guarino, sviluppo di una camera centrale con guanti integrati, passaggio controllato dei campioni, appoggio materiali separato, interno inox e illuminazione esterna alla zona di lavoro.",
    result: "Il concept diventò una Virus 3 Classe III industriale attraverso una costruzione più semplice, scelta dall’azienda per vincoli ricostruiti come economici, produttivi e di rischio.",
    implication: "La semplificazione può essere la prima tappa. Senza roadmap e business case, rischia di diventare la rinuncia definitiva alla visione originaria.",
    featured: true,
    fundamental: true,
  },
  {
    id: "mb301",
    number: "08",
    title: "Un quadro diverso senza ricominciare da zero",
    context: "A.R. Quadri",
    period: "2015–2025",
    capability: "Prodotto",
    summary: "Power Center, MCC e quadri BT ricondotti a un’unica proposta di carpenteria modulare.",
    premise: "Ogni nuova configurazione rischiava di moltiplicare componenti, regole di montaggio e soluzioni specifiche.",
    move: "Una piattaforma comune con risalita configurabile, componenti ripetibili e una logica coerente per sbarre, aerazione e accessi.",
    result: "MB301 arrivò al prototipo e alla documentazione di progetto; il passaggio alla produzione si fermò davanti ai costi di certificazione.",
    implication: "Una piattaforma di prodotto riduce la complessità solo quando l’impresa può sostenere anche l’investimento necessario ad adottarla.",
    fundamental: true,
  },
  {
    id: "goppion-anta",
    number: "09",
    title: "Il problema non era la cerniera. Era il pavimento",
    context: "Goppion · Museo Archeologico di Tebe",
    period: "2012–2015",
    capability: "Prodotto",
    summary: "Un’anta in vetro 6+6 di circa sei per tre metri ripensata separando sostegno del peso e guida del movimento.",
    premise: "Peso, deformazione e usura avrebbero compromesso nel tempo precisione, accessibilità e sicurezza se l’anta fosse stata trattata come una porta ingrandita.",
    move: "Trasferimento del carico su cuscinetti a pavimento e governo della traiettoria mediante una ruota collocata lontano dalla cerniera.",
    result: "Una cinematica nella quale il pavimento sosteneva il peso e la geometria guidava il movimento, senza affidare entrambe le funzioni alla cerniera.",
    implication: "Il problema visibile può essere soltanto il punto in cui una causa strutturale produce il proprio effetto.",
    featured: true,
  },
  {
    id: "stabilimento-aef",
    number: "10",
    title: "Il risultato operativo diventò una piegatrice",
    context: "AEF · Alfa Electrical Factory",
    period: "2006–2008",
    capability: "Reparto",
    summary: "Budget, KPI, persone, capacità e investimenti governati come un unico sistema operativo, distinto dalla P&L corporate completa.",
    premise: "Lo stabilimento meccanico produceva Power Center e linee Master Block, ma il suo futuro dipendeva dalla capacità di collegare risultato annuale e capitale produttivo.",
    move: "Governo del risultato operativo e degli investimenti ordinari, con business case per il CAPEX e lettura congiunta di capacità, marginalità e priorità tecniche.",
    result: "In almeno un esercizio gli obiettivi furono superati e l’avanzo finanziò una piegatrice CNC Vimercati senza ricorso al budget ordinario della sede.",
    implication: "Il risultato economico diventa industriale quando viene trasformato in capacità futura.",
    featured: true,
  },
  {
    id: "power-center",
    number: "11",
    title: "Vedere il calore prima che diventasse un guasto",
    context: "A.R. Quadri · Termografia preventiva",
    period: "2020",
    capability: "Reparto",
    summary: "Reti inox, strumenti e dimensioni della finestra verificati per rendere osservabili i codoli senza rinunciare alla segregazione.",
    premise: "La protezione dell’operatore poteva nascondere alla termocamera proprio i codoli nei quali un’anomalia avrebbe anticipato guasto o cortocircuito. Una finestra da 100 × 100 mm non rendeva inoltre leggibili tutte le quattro fasi del dispositivo provato.",
    move: "Confronto a distanze differenti fra rete inox fine e maglia da 5 mm, usando termocamere FLIR e Chauvin Arnoux e osservando trasparenza termica, messa a fuoco e campo visivo utile.",
    result: "La relazione tecnica del 23 giugno 2020, firmata M. Zago, raccomandò Chauvin Arnoux, rete fine e una finestra di almeno 120 × 120 mm, preferibilmente 130 × 130 mm. La maglia da 5 mm interferiva con la messa a fuoco e richiedeva continui adattamenti.",
    implication: "La manutenzione preventiva comincia quando il rischio diventa osservabile prima di trasformarsi in fermo o danno.",
  },
  {
    id: "standard-ar-quadri",
    number: "12",
    title: "Standardizzare senza irrigidire",
    context: "A.R. Quadri",
    period: "2015–2025",
    capability: "Reparto",
    summary: "Una base tecnica comune per Power Center, MCC e quadri BT, senza cancellare le configurazioni richieste dalle singole commesse.",
    premise: "Accessi, risalite, aerazione, sistemi sbarre e configurazioni cambiavano da quadro a quadro. Il rischio era ripetere ogni volta anche decisioni già risolte, affidandole alla memoria dei singoli.",
    move: "Architetture meccaniche, carpenteria, sistemi sbarre fino a 6000 A, regole costruttive, manuali, specifiche e componenti ricorrenti furono ricondotti a una base condivisa. La configurazione di commessa restava variabile.",
    result: "La funzione meccanica poté sostenere una produzione indicativa di circa cento colonne l’anno distinguendo ciò che richiedeva progettazione da ciò che poteva essere riutilizzato con coerenza.",
    implication: "Standardizzare non significa rendere uguali i quadri. Significa decidere una volta sola ciò che non crea valore decidere di nuovo.",
  },
  {
    id: "metalquadri",
    number: "13",
    title: "Trasferire una fabbrica senza fermarla",
    context: "Metalquadri",
    period: "2008–2011",
    capability: "Fabbrica",
    summary: "Il trasferimento da San Giuliano Milanese a Lodi Vecchio e, in una fase successiva, il coordinamento operativo dell’azienda durante la lunga assenza dell’amministratore delegato.",
    premise: "Il trasferimento richiedeva continuità fra commesse, persone e impianti. Solo successivamente, durante l’assenza dell’amministratore delegato, progettazione, acquisti, clienti e produzione dovettero convergere sotto un coordinamento operativo più ampio.",
    move: "Prima furono governate sequenza e ripartenza del nuovo stabilimento. Nella fase successiva Manuel coordinò circa venti persone e tenne insieme uffici, nesting, laser, laser 3D, laser tubo e produzione attorno alle priorità delle commesse.",
    result: "Il trasferimento preservò la continuità operativa; il coordinamento successivo mantenne unite le dipendenze fra cliente, progettazione, acquisti e reparto. Il precedente claim di record interno resta escluso per assenza di baseline.",
    implication: "La continuità non fu un solo episodio: prima il sistema cambiò luogo, poi dimostrò di poter reggere un vuoto di guida operativa.",
    featured: true,
  },
  {
    id: "impresa-legibile",
    number: "14",
    title: "Prima di trasformare, rendere leggibile l’impresa",
    context: "Diagnosi e governo della trasformazione · caso controllato",
    period: "2025–presente",
    capability: "Fabbrica",
    summary: "Processi, responsabilità, dipendenze e resistenze ricondotti a una mappa comune prima di scegliere priorità, strumenti e sequenza.",
    premise: "Le iniziative apparivano separate perché ogni funzione vedeva il proprio tratto del lavoro. Procedure dichiarate, prassi reali, conoscenza individuale e autorità decisionale non componevano ancora una rappresentazione condivisa dell’impresa.",
    move: "Mappatura trasversale di direzione, progettazione, produzione, magazzino e sistemi informativi; distinzione fra stato reale e stato dichiarato; definizione di responsabilità, gate, alleati, rischi di adozione e primi risultati visibili.",
    result: "La trasformazione venne ricondotta a una sequenza governabile. Standard, codifiche, flussi, investimenti e sistemi digitali poterono dipendere dalla stessa lettura; l’adozione resta in corso e il risultato appartiene al lavoro congiunto dell’organizzazione.",
    implication: "Prima di cambiare l’impresa bisogna costruire il modello comune con cui l’impresa possa vedere se stessa.",
    featured: true,
  },
  {
    id: "investimenti-industriali",
    number: "15",
    title: "Un investimento non è un acquisto. È una sequenza",
    context: "Capital allocation industriale · caso controllato",
    period: "2025–presente",
    capability: "Fabbrica",
    summary: "ERP, MES, infrastruttura, macchine, layout e logistica governati come portafoglio interdipendente invece che come acquisti corretti presi uno alla volta.",
    premise: "Ogni investimento poteva essere tecnicamente giustificabile e tuttavia indebolire il programma se prerequisiti, tempi di assorbimento, risorse e dipendenze fossero rimasti incoerenti.",
    move: "Business case, separazione CAPEX e OPEX, confronti TCO, analisi di rischio e sequenziamento tecnico furono usati per rendere espliciti trade-off, prerequisiti e capacità organizzativa necessaria.",
    result: "Le alternative confluirono in un programma comune leggibile dalla Direzione. Preventivi, approvazioni e benefici attesi restano distinti dai consuntivi; implementazione e risultati appartengono al lavoro congiunto di team, consulenti e fornitori.",
    implication: "Il capitale produce trasformazione soltanto quando ogni acquisto prepara le condizioni per il successivo.",
    featured: true,
  },
  {
    id: "logistica-industriale",
    number: "16",
    title: "Il magazzino non era spazio. Era flusso",
    context: "Logistica industriale · caso controllato",
    period: "2025–presente",
    capability: "Fabbrica",
    summary: "Layout, inventario, magazzino verticale, scaffali, picking, resi, formazione e sistemi trattati come un’unica capacità industriale.",
    premise: "Installare una macchina dentro un flusso ambiguo avrebbe automatizzato soltanto lo stoccaggio. Disponibilità reale, responsabilità, inventario, movimentazioni e restituzioni avrebbero continuato a produrre eccezioni.",
    move: "Il business case del magazzino verticale fu collegato al ridisegno fisico, alla preparazione del pavimento e degli scaffali, all’inventario, alle regole di picking e reso, alla formazione e all’integrazione ERP/MES.",
    result: "L’acquisto divenne un programma logistico unitario con dipendenze e gate espliciti. Il lavoro è in corso: benefici attesi e date di piano non vengono presentati come ROI o risultato già consuntivato.",
    implication: "Il magazzino crea capacità quando governa il percorso del materiale, non quando aumenta soltanto la densità dello spazio.",
    featured: true,
  },
  {
    id: "sistema-operativo-industriale",
    number: "17",
    title: "Dall’ERP al reparto: un solo sistema operativo",
    context: "ERP, MRP, MES e tracciabilità · caso controllato",
    period: "2025–presente",
    capability: "Sistema",
    summary: "Scelta dell’architettura, readiness, pianificazione, raccolta dati e tracciabilità ricondotte alla stessa catena operativa.",
    premise: "Preventivazione, CAD/CAM, distinte, cicli, produzione e avanzamento vivevano in strumenti e tempi differenti. Scegliere un software non avrebbe risolto lo spazio fra ciò che il sistema registra e ciò che il reparto deve realmente fare.",
    move: "Confronto multi-scenario su cinque anni, separazione CAPEX/OPEX, valutazione di integrazioni e rischi, piano RACI, gate di go-live e introduzione progressiva del MES vicino all’evento produttivo.",
    result: "È stata costruita l’architettura che collega scelta, adozione e controllo. Il go-live completo resta futuro: la prova riguarda qualità della decisione e governance della readiness, non implementazione conclusa o benefici quantitativi già ottenuti.",
    implication: "Il sistema operativo industriale esiste quando il dato nasce insieme al lavoro e può ancora modificare una decisione.",
    featured: true,
  },
  {
    id: "intelligenza-industriale",
    number: "18",
    title: "Dai documenti all’intelligenza industriale",
    context: "Infrastruttura, conoscenza, dati e IA · caso controllato",
    period: "2025–presente",
    capability: "Sistema",
    summary: "Continuità tecnologica, fonti governate, modello dati operativo, Hyper Nexum e IA composti come livelli della stessa memoria industriale.",
    premise: "Ridondanza hardware, file reperibili e chat generative potevano produrre l’illusione di controllo senza garantire continuità, versione valida, provenienza della fonte o passaggio verificabile dal dato all’azione.",
    move: "Confronto risk-adjusted dell’infrastruttura; repository e regole di provenienza; sorgenti gestionali mantenute in sola lettura; modello interno separato; controlli preventivi e IA usata come interfaccia di recupero e supporto.",
    result: "Esistono una base infrastrutturale e nuclei operativi controllati; Hyper Nexum e i flussi IA restano in sviluppo. Il portfolio non espone dati, automazioni o documenti interni e non presenta la piattaforma come prodotto enterprise concluso.",
    implication: "L’intelligenza industriale nasce quando una risposta può risalire alla fonte e un dato può diventare azione senza perdere governo.",
    featured: true,
  },
  {
    id: "d2-racing",
    number: "19",
    title: "In due dovevamo operare come una struttura molto più grande",
    context: "D2 Racing Sport Europe · impresa cofondata",
    period: "2005–2006",
    capability: "Sistema",
    summary: "E-commerce HTML, PayPal, fornitore cinese, media specializzati e presenza nei paddock collegati da una struttura di due persone.",
    premise: "Prodotto, comunicazione tecnica, pagamento, ricambi e presenza nelle competizioni sportive dovevano funzionare senza la struttura indiretta di un’azienda più grande.",
    move: "Costruzione del sito e del carrello, gestione della relazione tecnica con il fornitore, pubblicità di settore e disponibilità operativa dei ricambi nei campionati drifting.",
    result: "D2 collegò prodotto, canale digitale e comunità racing; MZB non contiene risultati commerciali quantitativi e il caso non li inventa.",
    implication: "Un sistema ben disegnato può amplificare una struttura piccola senza fingere che sia grande.",
    featured: true,
    fundamental: true,
  },
];

const fundamentalCaseOrder = [
  "d2-racing",
  "wmc-inside",
  "safemate-classe-ii",
  "virus-3",
  "robolaser-applyca",
  "mb301",
] as const;

const fundamentalRank = new Map<string, number>(
  fundamentalCaseOrder.map((id, index) => [id, index]),
);

export const cases: CaseStudy[] = [...chronologicalCases].sort((a, b) => {
  const aRank = fundamentalRank.get(a.id);
  const bRank = fundamentalRank.get(b.id);

  if (aRank !== undefined && bRank !== undefined) return aRank - bRank;
  if (aRank !== undefined) return -1;
  if (bRank !== undefined) return 1;
  return Number(a.number) - Number(b.number);
});

export const caseDomains: Record<string, Domain[]> = {
  "rettifiche-cnc": ["Meccanica", "Automazione", "Industrializzazione"],
  "automazione-piegatura": ["Meccanica", "Automazione", "Sistemi digitali", "Operations"],
  "robolaser-applyca": ["Meccanica", "Automazione", "Industrializzazione"],
  "wmc-inside": ["Meccanica", "Design di prodotto", "Industrializzazione", "Sistemi digitali"],
  "fiumicino-digital": ["Meccanica", "Design di prodotto", "Industrializzazione"],
  "safemate-classe-ii": ["Meccanica", "Design di prodotto", "Industrializzazione", "Operations"],
  "virus-3": ["Meccanica", "Design di prodotto", "Industrializzazione"],
  "mb301": ["Meccanica", "Design di prodotto", "Industrializzazione", "Governance"],
  "goppion-anta": ["Meccanica", "Design di prodotto", "Industrializzazione"],
  "stabilimento-aef": ["Meccanica", "Industrializzazione", "Operations", "Governance"],
  "power-center": ["Meccanica", "Industrializzazione", "Operations"],
  "standard-ar-quadri": ["Meccanica", "Automazione", "Industrializzazione", "Operations"],
  metalquadri: ["Industrializzazione", "Operations", "Governance"],
  "impresa-legibile": ["Industrializzazione", "Operations", "Sistemi digitali", "Governance"],
  "investimenti-industriali": ["Industrializzazione", "Operations", "Sistemi digitali", "Governance"],
  "logistica-industriale": ["Automazione", "Industrializzazione", "Operations", "Sistemi digitali"],
  "sistema-operativo-industriale": ["Automazione", "Operations", "Sistemi digitali", "Dati & IA", "Governance"],
  "intelligenza-industriale": ["Operations", "Sistemi digitali", "Dati & IA", "Governance"],
  "d2-racing": ["Design di prodotto", "Industrializzazione", "Operations", "Governance"],
};

export const caseProjection: Record<string, string> = {
  "rettifiche-cnc": "Quanta precisione dipende ancora da chi sa compensare il sistema a memoria?",
  "automazione-piegatura": "Quale limite attribuito alla macchina nasce in realtà nei passaggi che la alimentano, riposizionano o identificano?",
  "robolaser-applyca": "Quale buona idea resta confinata dentro il perimetro tecnico che l’ha generata?",
  "wmc-inside": "Quale convergenza è già possibile, ma la vostra organizzazione continua a leggere per categorie separate?",
  "fiumicino-digital": "Quale scelta funziona nel prototipo ma non è ancora stata progettata per ripetersi in tutte le unità e nel contesto reale?",
  "safemate-classe-ii": "Il vostro nuovo prodotto dispone già del sistema industriale necessario per diventare capacità reale?",
  "virus-3": "Dove sicurezza, utilizzatore, pulibilità e produzione vengono ancora ottimizzati separatamente?",
  "mb301": "Quale innovazione tecnicamente corretta non ha ancora incontrato le condizioni economiche della propria adozione?",
  "goppion-anta": "Quale problema state cercando di correggere nel punto in cui appare, invece che nel punto in cui nasce?",
  "stabilimento-aef": "Il risultato operativo del reparto resta un consuntivo o viene trasformato in nuova capacità industriale?",
  "power-center": "Quale rischio potrebbe essere reso visibile mentre è ancora un’anomalia, invece che dopo essere diventato fermo o danno?",
  "standard-ar-quadri": "Quale conoscenza critica vive ancora nella memoria dei singoli invece che nel processo?",
  metalquadri: "Se cambiasse il luogo, una persona o una priorità, quali dipendenze fermerebbero davvero la fabbrica?",
  "impresa-legibile": "La vostra trasformazione dipende da una rappresentazione comune dell’impresa o da mappe diverse possedute dalle singole funzioni?",
  "investimenti-industriali": "I vostri investimenti compongono un sistema o competono tra loro per produrre risultati locali?",
  "logistica-industriale": "L’automazione sta governando il percorso completo del materiale o soltanto il punto in cui viene stoccato?",
  "sistema-operativo-industriale": "Il dato nasce dove accade il lavoro e con gate sufficienti a decidere se il sistema è davvero pronto?",
  "intelligenza-industriale": "Una risposta aziendale può risalire alla fonte e diventare azione senza perdere provenienza, controllo e responsabilità?",
  "d2-racing": "Quale parte della capacità dipende davvero dalle dimensioni della struttura e quale invece dalla qualità del sistema?",
};
