import type { Capability, Domain } from "./cases";

export type LensName = Capability | Domain;

export const lensMessages: Record<LensName, string> = {
  Macchina: "La precisione non vive nella macchina. Vive nel processo che la rende ripetibile.",
  Prodotto: "Un’idea diventa potente quando l’impresa può costruirla, adottarla e mantenerla.",
  Reparto: "Il margine conta quando modifica ciò che il reparto potrà fare domani.",
  Fabbrica: "Una fabbrica è una rete di dipendenze prima di essere un luogo.",
  Sistema: "Prima di digitalizzare un’impresa, bisogna renderla leggibile.",
  Meccanica: "Entro nel dettaglio senza perdere l’architettura.",
  "Design di prodotto": "La forma deve funzionare per chi usa il prodotto e per chi dovrà costruirlo.",
  Automazione: "Automatizzare non significa muovere una macchina. Significa governare il flusso.",
  Industrializzazione: "La soluzione non è conclusa finché non diventa capacità.",
  Operations: "Persone, materiali, tempi e responsabilità devono convergere.",
  "Sistemi digitali": "Il software deve rappresentare il lavoro reale.",
  "Dati & IA": "Prima di chiedere all’IA di rispondere, l’impresa deve decidere che cosa sa.",
  Governance: "Decidere significa anche fermare il sistema prima che il rischio diventi danno.",
};

export type FeaturedStory = {
  id: string;
  index: string;
  eyebrow: string;
  period: string;
  title: string;
  opening: string;
  body: string;
  residue: string;
  image?: string;
  gallery?: string[];
  youtube?: string;
  sources?: { label: string; href: string }[];
  tone?: "bone" | "forest" | "ink";
  layout?: "wide" | "split" | "portrait";
};

export const featuredStories: FeaturedStory[] = [
  {
    id: "rettifiche-cnc",
    index: "01",
    eyebrow: "BIC Italia | Co Stampi · Macchina",
    period: "1994—2002",
    title: "La quota cambiava con la temperatura.",
    opening: "Il reparto rettifiche lavorava ancora su macchine manuali quando a un giovane tecnico appena arrivato fu affidato il passaggio al CNC. La Kellenberger era complessa, il corso avveniva con un tecnico tedesco e la lingua non aiutava. Ma la difficoltà più seria apparve dopo: sulle tolleranze millesimali, la quota continuava a cambiare.",
    body: "Compensare ancora la macchina avrebbe corretto il sintomo, non la causa. Cercando ciò che variava intorno alla lavorazione emerse il legame con la temperatura del fluido di processo. Un refrigeratore rese la rettifica più stabile, aumentò la velocità operativa e ridusse i non conformi. Poi un PC aziendale recuperato portò programmi e storico fuori dal bordo macchina: ciò che era stato imparato non rimaneva più prigioniero del turno o della memoria. La pressione del responsabile di fabbrica, compresa pienamente soltanto anni dopo, aveva trasformato un incarico precoce in una scuola di responsabilità.",
    residue: "La prima lezione non fu usare una macchina nuova. Fu capire che la causa può vivere fuori dal punto che tutti stanno osservando.",
    image: "/MZOS/assets/kellenberger-ur-175-1000.webp",
    tone: "ink",
    layout: "split",
  },
  {
    id: "wmc-inside",
    index: "02",
    eyebrow: "Hantarex · LCD 40 WMC Inside",
    period: "2004—2005",
    title: "La smart TV non aveva ancora un nome.",
    opening: "A casa Windows Media Center era già più di un software. Mostrava una traiettoria: televisione, computer, rete, fotografie, musica e video sarebbero confluiti nello stesso oggetto. Quando Hantarex lasciò aperta la possibilità di sviluppare quell'idea, il lavoro continuò anche fuori orario.",
    body: "Il primo prototipo funzionante fu ideato, progettato, integrato e assemblato interamente in prima persona. Dentro un LCD da 40 pollici convivevano un PC estraibile, Windows XP Media Center Edition, disco, DVD, rete, USB, lettore di schede e tuner; un solo telecomando governava TV e contenuti digitali. Il design su due piani alleggeriva la presenza del volume posteriore: doveva continuare a sembrare un televisore, non un computer avvitato a uno schermo. Il manuale Hantarex non descrive un concept: presenta un prodotto reale, capace di registrare e mettere in pausa la TV, navigare, archiviare contenuti e lavorare anche in ambienti business. WMC Inside entrò nella produzione commerciale Hantarex. L'azienda e il prodotto ricevettero due Green Button Award Microsoft, nel 2004 e nel 2005, consegnati da Bill Gates. Anni dopo il mercato avrebbe chiamato tutto questo smart TV.",
    residue: "Non era una previsione raccontata dopo. Era già un oggetto costruito, commercializzato e premiato.",
    gallery: ["/MZOS/assets/wmc-inside-angle.webp", "/MZOS/assets/wmc-inside-front.webp", "/MZOS/assets/wmc-manual-page-2.webp"],
    tone: "bone",
    layout: "wide",
  },
  {
    id: "robolaser-applyca",
    index: "03",
    eyebrow: "Applyca · RoboLaser STEflex",
    period: "18 giugno 2025",
    title: "«Alla fine l’abbiamo fatta.»",
    opening: "Il messaggio arrivò dopo che l’idea aveva già attraversato tempo, aziende e persone: «Ciao Manuel. Alla fine l’abbiamo fatta». Non annunciava soltanto una macchina finita. Restituiva forma concreta a un confronto tecnico nato molto prima, durante una fiera.",
    body: "Il concept metteva insieme un vero laser e un robot antropomorfo, chiedendo alla stessa architettura di lavorare sia lamiera piana sia quadri elettrici già montati. Applyca trasformò quelle indicazioni funzionali in una macchina reale e ne sviluppò l’esecuzione: il prodotto pubblico documenta anche taglio 3D, lavorazione del tubo, filettatura e maschiatura in un unico setup automatico. Nel giugno 2025 arrivò la conferma scritta che la macchina era stata progettata seguendo quelle indicazioni. La parola scelta non fu vendetta, ma soddisfazione: vedere un’intuizione diventare realtà nelle mani di una buona impresa, senza confondere il concept con la progettazione esecutiva che appartiene ad Applyca.",
    residue: "Le idee industriali più forti continuano a lavorare anche fuori dal luogo in cui sono nate.",
    youtube: "XCbkofQjKog",
    tone: "ink",
    layout: "wide",
  },
  {
    id: "fiumicino-digital",
    index: "03",
    eyebrow: "Metalquadri · CBS Outdoor · Fiumicino Digital",
    period: "2008—2011",
    title: "Diciannove totem non erano diciannove prototipi.",
    opening: "La commessa CBS arrivò a Metalquadri attraverso una società consociata: diciannove totem digitali portrait da 55 pollici destinati al circuito Air Terminal di Fiumicino. Il design e la realizzazione furono affidati a Manuel, mentre CBS UK manteneva la supervisione estetica. Non si trattava di proporre un concept, ma di trasformare una scelta formale in diciannove prodotti installabili.",
    body: "Per conservare la purezza del frontale, il vetro doveva restare privo di cornici e fissaggi visibili. Manuel scelse il 3M VHB dopo averne studiato caratteristiche e applicazione. I colleghi non erano convinti: in quegli anni quel materiale veniva ancora letto come un semplice biadesivo, non come parte affidabile dell’architettura del prodotto. La decisione fu mantenuta e la prima fornitura venne realizzata e installata con quella soluzione. I totem integravano aggiornamento in tempo reale, Wi-Fi e proximity marketing; il PDF di progetto indica un’esposizione di circa 975.000 passeggeri ogni quattordici giorni.",
    residue: "La purezza formale non nacque eliminando la tecnica. Nacque scegliendo una tecnica abbastanza affidabile da poter scomparire.",
    image: "/MZOS/assets/fiumicino.webp",
    tone: "forest",
    layout: "wide",
  },
  {
    id: "safemate-classe-ii",
    index: "04",
    eyebrow: "Euroclone · SafeMate Classe II",
    period: "2015—2018",
    title: "Sei mesi per costruire il prodotto e il sistema che lo avrebbe prodotto.",
    opening: "Il foglio era bianco, ma il prodotto non poteva esserlo. Una cabina di sicurezza microbiologica doveva proteggere l’operatore, contenere il rischio, restare pulibile, superare la certificazione, essere riconoscibile e poter nascere in tre taglie. In sei mesi, nessuna fase poteva aspettare che la precedente fosse perfettamente conclusa.",
    body: "Il lavoro fu impostato come un’unica catena. Concept, architettura fisica e caratteristiche funzionali definirono il prodotto prima che le competenze specialistiche si separassero. Modellazione 3D, stampa FDM e lavorazioni laser anticiparono verifiche e correzioni; prototipi e prove rimasero dentro il progetto, non alla sua fine. Il coordinamento arrivò fino alla certificazione e all’avvio produttivo, mentre elettronica, dettagli esecutivi, impianti, lavorazioni e approvazioni economiche restarono responsabilità del team e dell’azienda. In circa sei mesi SafeMate EVO entrò a catalogo e in produzione, certificata TÜV Nord e disponibile in tre taglie. Le linee furono dimensionate per circa 5.000 unità annue: capacità prevista, non volume venduto. La scala costruita allora si legge anche nella traiettoria successiva: BioAir dichiara una rete di oltre settanta distributori e venti mercati principali; in Australia LAF Technologies riferisce oltre 2.000 cabine biologiche BioAir fornite e assistite. In Europa, la famiglia SafeMate nelle sue diverse generazioni è stimata nell’ordine di diverse migliaia di unità operative. Sono numeri della piattaforma aziendale, non vendite personali né il consuntivo della sola EVO.",
    residue: "I sei mesi furono la prova. Il risultato vero fu lasciare insieme un prodotto e il sistema capace di ripeterlo.",
    gallery: ["/MZOS/assets/safemate-evo-catalog.webp", "/MZOS/assets/safemate-evo-front.webp", "/MZOS/assets/safemate-evo-product.webp"],
    youtube: "N7tTnf9b77M",
    sources: [
      { label: "Catalogo BioAir", href: "https://www.bioair.it/media/resources/BioAir_Catalogo_Generale_Web.pdf" },
      { label: "Rete internazionale BioAir", href: "https://www.bioair.it/en/bioair/references.php" },
      { label: "Australia: oltre 2.000 cabine", href: "https://laftech.com.au/product/class-ii-biological-safety-cabinets/" },
    ],
    tone: "bone",
    layout: "wide",
  },
  {
    id: "virus-3",
    index: "05",
    eyebrow: "Euroclone · Virus 3 Classe III",
    period: "2015—2018",
    title: "Il rischio doveva restare dentro. L’operatore doveva poter lavorare.",
    opening: "Una cabina di Classe III deve creare una barriera totale. Ma se ogni superficie aggiunge un punto difficile da pulire e ogni gesto diventa più complesso, il contenimento protegge l’operatore mentre gli sottrae la possibilità di lavorare bene. Virus 3 nacque trattando sicurezza, pulibilità, ergonomia e accessibilità come un solo problema.",
    body: "Il progetto fu sviluppato con Michele Guarino, mentore professionale e tecnico. Nel lavoro Euroclone, lo studio di T3SS, T4SS, Yersinia e Salmonella serviva a comprendere il rischio biologico prima di tradurlo in macchina e processo. Il concept organizzava il lavoro attorno a una camera centrale con guanti integrati: un modulo laterale controllava il passaggio dei campioni, l’altro separava l’appoggio dei materiali. L’interno in acciaio inox riduceva le discontinuità; l’illuminazione restava fuori dalla camera per non aggiungere superfici e punti critici; la forma esterna rendeva immediatamente leggibili le zone operative. L’azienda portò poi in produzione una costruzione più semplice. Per quanto ricostruito da Manuel, costi, complessità, tempi e rischio tecnico pesarono sulla scelta. Erano vincoli legittimi. Il limite, compreso dopo, non fu semplificare la prima versione, ma non trasformarla nella prima tappa di una roadmap capace di rendere progressivamente adottabile il concept originario.",
    residue: "Una soluzione tecnica diventa industria quando anche il suo valore e il suo rischio hanno un percorso adottabile.",
    gallery: ["/MZOS/assets/virus-concept.webp", "/MZOS/assets/virus-3-concept-render.webp", "/MZOS/assets/virus-product.webp"],
    youtube: "N7tTnf9b77M",
    tone: "forest",
    layout: "split",
  },
  {
    id: "stabilimento-aef",
    index: "06",
    eyebrow: "AEF · Reparto",
    period: "2006—2008",
    title: "Il risultato operativo diventò una piegatrice.",
    opening: "In AEF lo stabilimento meccanico non era governato soltanto come centro di esecuzione. Budget, KPI annuali, persone, capacità produttiva, investimenti e risultato operativo componevano lo stesso perimetro di responsabilità, distinto dalla politica commerciale generale dell’azienda.",
    body: "La gestione collegava Power Center, linee Master Block, produzione e investimenti. In almeno un esercizio gli obiettivi furono superati; l’avanzo generato finanziò una piegatrice CNC Vimercati senza ricorrere al budget ordinario della sede. Il punto non era acquistare una macchina in più. Era trasformare un risultato consuntivo in nuova capacità, rendendo visibile il rapporto fra decisione operativa, capitale e futuro dello stabilimento.",
    residue: "Il margine conta quando cambia ciò che il sistema potrà fare dopo.",
    gallery: ["/MZOS/assets/aef-1.webp", "/MZOS/assets/aef-2.webp"],
    tone: "bone",
    layout: "split",
  },
  {
    id: "power-center",
    index: "11",
    eyebrow: "A.R. Quadri · Termografia preventiva",
    period: "2020",
    title: "Vedere il calore prima che diventasse un guasto.",
    opening: "Nei quadri in funzione, il calore può anticipare un allentamento, un contatto imperfetto o un sovraccarico. Ma le segregazioni che proteggono l’operatore possono nascondere alla termocamera proprio codoli e connessioni che devono restare osservabili. Il problema non era quindi soltanto scegliere uno strumento: era rendere leggibile il rischio senza indebolire la protezione.",
    body: "Le prove confrontarono due segregazioni inox, una rete molto fine e una maglia da 5 mm, usando termocamere FLIR e Chauvin Arnoux a distanze differenti. La relazione del 23 giugno 2020, firmata M. Zago, documenta l’effetto della protezione sulla leggibilità: con la maglia larga la camera tendeva a mettere a fuoco la rete, costringendo a variare distanza e fuoco; la rete fine risultava invece quasi trasparente allo strumento Chauvin Arnoux. Il documento raccomandò quindi camera Chauvin Arnoux, rete fine e l’ampliamento della finestra di osservazione del dispositivo NSX630 dai 100 × 100 mm provati ad almeno 120 × 120 mm, preferibilmente 130 × 130 mm, per rendere osservabili tutte le quattro fasi. La termografia preventiva diventava così un requisito della segregazione, non un controllo aggiunto a quadro già costruito.",
    residue: "La manutenzione preventiva comincia molto prima dell’ispezione: comincia quando il quadro viene progettato per rendere visibile ciò che potrebbe degradarsi.",
    tone: "forest",
    layout: "wide",
  },
  {
    id: "standard-ar-quadri",
    index: "12",
    eyebrow: "A.R. Quadri · Standard tecnici",
    period: "2015—2025",
    title: "Standardizzare senza irrigidire.",
    opening: "Power Center, MCC e quadri BT non erano prodotti identici: cambiavano accessi, risalite, aerazione, sistemi sbarre e configurazione della commessa. Il problema non era eliminare queste differenze. Era evitare che insieme alle varianti necessarie tornassero ogni volta anche decisioni tecniche già risolte.",
    body: "Il lavoro separò i due livelli. Architetture meccaniche, carpenteria, sistemi sbarre fino a 6000 A, regole costruttive, manuali, specifiche e componenti ricorrenti furono portati dentro una base tecnica condivisa. La configurazione richiesta dal cliente rimaneva variabile, ma non obbligava più a reinventare ogni regola che la sosteneva. Questa distinzione permise alla funzione meccanica di sostenere una produzione indicativa di circa cento colonne l’anno con riferimenti più coerenti e minore dipendenza dalla memoria individuale.",
    residue: "Standardizzare non significò rendere uguali i quadri. Significò decidere una volta sola ciò che non creava valore decidere di nuovo.",
    tone: "bone",
    layout: "wide",
  },
  {
    id: "automazione-piegatura",
    index: "07",
    eyebrow: "A.R. Quadri · Automazione autonoma",
    period: "2015—2025",
    title: "Il limite non era la piegatrice. Era la cinematica del robot.",
    opening: "Il video mostra una cella, non una piegatrice isolata: pressa, braccio robotico, tavola di riposizionamento sul piano di carico e laser incisore partecipano alla stessa sequenza. Il limite appariva durante la piegatura, ma nasceva nei cambi di presa e negli orientamenti che il robot non poteva risolvere in un solo movimento.",
    body: "L’integrazione fu costruita attorno al percorso completo del pezzo. La tavola sul piano di carico consentiva di riposizionarlo quando la cinematica del braccio richiedeva un nuovo assetto; il robot lo riportava alla piegatrice; il laser incideva logo, numero seriale e gli altri dati necessari all’identificazione. Piegatura, manipolazione, riposizionamento e marcatura smisero così di essere isole tecniche. Le fonti disponibili non contengono metriche prima e dopo: la prova pubblica è l’integrazione visibile dell’intero flusso.",
    residue: "Il limite non apparteneva a una delle macchine. Apparteneva allo spazio fra una macchina e la successiva.",
    gallery: ["/MZOS/assets/ar-1.webp", "/MZOS/assets/ar-2.webp", "/MZOS/assets/ar-3.webp"],
    tone: "ink",
    layout: "wide",
  },
  {
    id: "mb301",
    index: "08",
    eyebrow: "A.R. Quadri · MB301",
    period: "2015—2025",
    title: "Il problema non era progettare un altro quadro. Era smettere di ripartire ogni volta.",
    opening: "Power Center, MCC e quadri BT potevano richiedere accesso frontale o posteriore, risalite diverse, sistemi sbarre, aerazione e sequenze di assemblaggio differenti. Ogni configurazione tecnicamente corretta aggiungeva però una nuova eccezione alla fabbrica.",
    body: "MB301 nacque per cambiare il livello del problema. Invece di aggiungere un’altra carpenteria alla famiglia, cercava una piattaforma modulare capace di assorbire configurazioni diverse. La risalita poteva spostarsi a destra o a sinistra; componenti e geometrie venivano pensati per ripetersi; sbarre, aerazione, accessi e montaggio dovevano restare coerenti mentre cambiava il quadro. Era un ottimo progetto perché trasferiva complessità dal reparto alla regola di prodotto: meno soluzioni isolate da ricordare, maggiore ripetibilità e una base più credibile per produrre in modo modulare e scalabile. Il lavoro arrivò al prototipo e a tavole di progetto firmate. Non entrò in produzione perché l’azienda non riuscì a sostenere i costi della certificazione necessaria alla fase successiva.",
    residue: "La geometria era stata risolta. Restava da finanziare il diritto di portarla sul mercato.",
    image: "/MZOS/assets/mb301.webp",
    tone: "bone",
    layout: "wide",
  },
  {
    id: "metalquadri",
    index: "08",
    eyebrow: "Metalquadri · Fabbrica",
    period: "2008—2011",
    title: "Trasferire una fabbrica senza fermarla.",
    opening: "Metalquadri trasferì lo stabilimento da San Giuliano Milanese a Lodi Vecchio continuando a gestire commesse, persone e impianti. Il trasloco fisico fu il primo passaggio. La lunga assenza dell’amministratore delegato avvenne dopo e aprì un problema diverso: mantenere unita la guida operativa dell’azienda.",
    body: "Nella prima fase, la continuità dipese dalla sequenza con cui impianti, attività e priorità vennero portati nella nuova sede e rimessi in condizione di produrre. Solo successivamente Manuel assunse di fatto il coordinamento operativo di circa venti persone, tenendo insieme uffici, nesting, laser, laser 3D, laser tubo e produzione. Cliente, progettazione, acquisti e reparto dovevano convergere ogni giorno anche in assenza del vertice operativo. Le fonti disponibili sostengono la continuità delle commesse; il precedente claim di record interno resta escluso perché privo di una baseline verificabile.",
    residue: "La continuità venne provata due volte: quando la fabbrica cambiò luogo e, dopo, quando dovette reggere un vuoto di guida.",
    image: "/MZOS/assets/metalquadri.webp",
    tone: "forest",
    layout: "wide",
  },
  {
    id: "goppion-anta",
    index: "09",
    eyebrow: "Goppion · Museo Archeologico di Tebe",
    period: "2012—2015",
    title: "Il problema non era la cerniera. Era il pavimento.",
    opening: "Il Museo Archeologico di Tebe fu il primo progetto simbolico dell’esperienza Goppion. Un’anta di circa sei per tre metri in vetro stratificato 6+6 non poteva essere trattata come una porta semplicemente più grande: peso, deformazione e usura avrebbero deciso nel tempo la qualità del movimento.",
    body: "Concentrare la risposta sulla cerniera avrebbe lasciato intatta la causa. La soluzione trasferì il carico su cuscinetti a pavimento, nel punto capace di sostenerlo, e governò la traiettoria con una ruota collocata lontano dalla cerniera. La geometria separava così due funzioni che una porta ordinaria sovrappone: sostenere il peso e guidare il movimento. Era un intervento dentro un sistema museale più ampio, nel quale meccanica, vetri pesanti, pneumatica, oleodinamica, illuminazione, microclima controllato e sicurezza dovevano convergere senza sottrarre attenzione alle opere.",
    residue: "Il rischio sembrava nella cerniera. Nasceva nel rapporto tra peso, pavimento e geometria.",
    image: "/MZOS/assets/tebe.webp",
    tone: "bone",
    layout: "split",
  },
  {
    id: "impresa-legibile",
    index: "14",
    eyebrow: "Trasformazione industriale · Diagnosi e governo",
    period: "2025—oggi",
    title: "Prima di trasformare, rendere leggibile l’impresa.",
    opening: "La trasformazione appariva come una somma di problemi locali: dati incompleti, flussi informali, responsabilità sovrapposte, strumenti separati e resistenze all’adozione. Intervenire punto per punto avrebbe prodotto iniziative corrette ma incompatibili.",
    body: "La prima architettura fu una mappa trasversale di direzione, progettazione, produzione, magazzino e sistemi informativi. Stato reale e procedure dichiarate vennero separati; dipendenze, responsabilità, priorità e gate decisionali furono ricondotti allo stesso quadro. Anche la resistenza entrò nel modello: non come ostacolo da forzare, ma come informazione su autorità, incentivi, rischio percepito e capacità di assorbimento. La mappa divenne il criterio comune da cui far dipendere standard, investimenti, logistica e digitale.",
    residue: "L’impresa cominciò a trasformarsi quando smise di essere descritta per funzioni e divenne leggibile come sistema.",
    tone: "ink",
    layout: "wide",
  },
  {
    id: "investimenti-industriali",
    index: "15",
    eyebrow: "Trasformazione industriale · Capital allocation",
    period: "2025—oggi",
    title: "Un investimento non è un acquisto. È una sequenza.",
    opening: "ERP, MES, infrastruttura, macchine, layout e logistica potevano essere difesi singolarmente. Il rischio era approvarli come oggetti indipendenti e scoprire dopo che ciascuno aspettava dati, spazi, competenze o decisioni che il programma non aveva ancora preparato.",
    body: "Business case, separazione CAPEX e OPEX, confronti TCO e analisi di rischio furono usati per leggere il portafoglio nel tempo. La domanda non era soltanto quale soluzione costasse meno, ma quale dipendenza dovesse essere risolta prima, quale capacità l’organizzazione potesse assorbire e quale acquisto rendesse possibile il successivo. Le alternative divennero così una sequenza con trade-off espliciti e responsabilità condivise con Direzione, funzione finanziaria, team, consulenti e fornitori.",
    residue: "Il capitale smette di finanziare oggetti quando comincia a costruire capacità cumulative.",
    tone: "bone",
    layout: "wide",
  },
  {
    id: "logistica-industriale",
    index: "16",
    eyebrow: "Trasformazione industriale · Logistica",
    period: "2025—oggi",
    title: "Il magazzino non era spazio. Era flusso.",
    opening: "Un magazzino verticale avrebbe aumentato la densità e automatizzato lo stoccaggio. Non avrebbe però corretto inventario incerto, responsabilità ambigue, picking, resi e movimenti nati fuori dalle regole.",
    body: "La macchina venne quindi trattata come l’ultima parte visibile di un ridisegno più ampio. Layout, pavimento, scaffali, inventario, criteri di ubicazione, picking, restituzioni, formazione e integrazione ERP/MES furono collegati nello stesso programma. Il business case rimase distinto dal consuntivo: approvazione e benefici attesi non vengono trasformati in risultati già ottenuti. La prova è la qualità della sequenza costruita per impedire che l’automazione rendesse soltanto più veloce un flusso ancora ambiguo.",
    residue: "Lo spazio si ottimizza con una macchina. Il flusso si governa ridisegnando tutto ciò che entra, esce e ritorna.",
    tone: "forest",
    layout: "wide",
  },
  {
    id: "sistema-operativo-industriale",
    index: "17",
    eyebrow: "Trasformazione industriale · ERP, MRP e MES",
    period: "2025—oggi",
    title: "Dall’ERP al reparto: un solo sistema operativo.",
    opening: "Preventivazione, CAD/CAM, distinte, cicli, pianificazione, produzione, tempi e tracciabilità vivevano in strumenti e momenti differenti. La scelta del software non poteva chiudere da sola lo spazio fra il dato registrato e il lavoro reale.",
    body: "Un confronto multi-scenario su cinque anni separò CAPEX e OPEX e valutò integrazione, scalabilità, migrazione e rischio. Il piano tradusse la scelta in fasi e responsabilità RACI. Il MES venne avvicinato all’evento produttivo, mentre gate di readiness su dati, processi, formazione, utilizzo e workaround resero esplicita la possibilità di raccomandare un go o un no-go. Il sistema resta in adozione: non vengono dichiarati implementazione conclusa, utilizzo stabilizzato o benefici quantitativi non ancora provati.",
    residue: "Il software diventa sistema operativo quando pianificazione, reparto e decisione usano la stessa realtà.",
    tone: "ink",
    layout: "wide",
  },
  {
    id: "intelligenza-industriale",
    index: "18",
    eyebrow: "Trasformazione industriale · Infrastruttura, dati e IA",
    period: "2025—oggi",
    title: "Dai documenti all’intelligenza industriale.",
    opening: "Un server ridondato non garantisce da solo continuità. Un file trovato non è necessariamente la versione valida. Una risposta dell’IA non è conoscenza se non può indicare la fonte da cui dipende.",
    body: "L’infrastruttura venne letta come parte della capacità produttiva, collegando piattaforme, rete, backup, ripristino e rischio di fermo. Sopra questa base furono costruiti repository, domini e regole di provenienza. Hyper Nexum mantenne le sorgenti gestionali in sola lettura e separò il modello interno, aggiungendo controlli preventivi, conferma prima dell’esecuzione e tracciabilità degli esiti. Soltanto a quel punto l’IA poteva diventare un’interfaccia di recupero e supporto, non una nuova autorità senza fonte. La piattaforma resta in sviluppo e i dettagli operativi rimangono riservati.",
    residue: "L’intelligenza industriale non nasce dalla quantità di dati, ma dalla continuità con cui fonte, decisione e azione restano verificabili.",
    tone: "ink",
    layout: "wide",
  },
];

export const caseMedia: Record<string, {
  image?: string;
  gallery?: string[];
  galleryCaptions?: string[];
  youtube?: string;
  caption?: string;
}> = {
  "rettifiche-cnc": { image: "/MZOS/assets/kellenberger-ur-175-1000.webp" },
  "automazione-piegatura": { youtube: "jtQdpsE051s" },
  "robolaser-applyca": { youtube: "XCbkofQjKog" },
  "wmc-inside": { gallery: ["/MZOS/assets/wmc-inside-angle.webp", "/MZOS/assets/wmc-inside-front.webp", "/MZOS/assets/wmc-manual-page-2.webp"] },
  "fiumicino-digital": { image: "/MZOS/assets/fiumicino.webp" },
  "safemate-classe-ii": {
    gallery: ["/MZOS/assets/safemate-evo-catalog.webp", "/MZOS/assets/safemate-evo-front.webp", "/MZOS/assets/safemate-evo-product.webp"],
    youtube: "N7tTnf9b77M",
  },
  "virus-3": {
    gallery: ["/MZOS/assets/virus-concept.webp", "/MZOS/assets/virus-3-concept-render.webp", "/MZOS/assets/virus-product.webp"],
    galleryCaptions: [
      "Studio concettuale Classe III 2.0 · non fotografia del prodotto realizzato",
      "Render di studio · ipotesi di come la macchina avrebbe potuto essere",
      "Versione industrializzata della cabina",
    ],
    youtube: "N7tTnf9b77M",
  },
  mb301: { image: "/MZOS/assets/mb301.webp" },
  "d2-racing": {
    gallery: [
      "/MZOS/assets/d2-brake-caliper.jpg",
      "/MZOS/assets/d2-coilovers.jpg",
      "/MZOS/assets/d2-paddock.jpg",
      "/MZOS/assets/d2-logo.png",
    ],
    galleryCaptions: [
      "Pinza freno D2 Racing Sport",
      "Sospensioni e componenti di regolazione",
      "Presenza D2 nelle competizioni sportive",
      "Marchio D2 Racing Sport Europe",
    ],
    youtube: "Q3d5KSSh6rI",
  },
  "stabilimento-aef": { gallery: ["/MZOS/assets/aef-1.webp", "/MZOS/assets/aef-2.webp"] },
  "power-center": {
    gallery: [
      "/MZOS/assets/termografia-flir00014.png",
      "/MZOS/assets/termografia-ca000817-029.webp",
    ],
    galleryCaptions: [
      "FLIR00014 · il punto caldo resta identificabile attraverso la rete fine",
      "Chauvin Arnoux IR_31 · la trama della maglia da 5 mm resta visibile",
    ],
  },
  metalquadri: { image: "/MZOS/assets/metalquadri.webp" },
  "goppion-anta": {
    image: "/MZOS/assets/tebe.webp",
    caption: "Immagine di contesto · Museo Archeologico di Tebe · non documenta l’anta specifica",
  },
};
